# -*- coding: utf-8 -*-
"""dark_pattern.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g5f2pITtVV5NiZ9CPmesC4u2Klxjr74O

import dataset
"""

import pandas as pd

df = pd.read_csv('/content/dataset.csv')

print("Dataset Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

print("Missing values:")
print(df.isnull().sum())

print("\nLabel distribution:")
print(df['label'].value_counts())

print("\nPattern Category distribution:")
print(df['Pattern Category'].value_counts())

print("Number of duplicate rows:", df.duplicated().sum())
print("Number of duplicate texts:", df['text'].duplicated().sum())
print("Number of unique page IDs:", df['page_id'].nunique())

"""dataset in category wise"""

for category in df['Pattern Category'].unique():
    print("\n" + "=" * 60)
    print("CATEGORY:", category)
    print("=" * 60)

    samples = df[df['Pattern Category'] == category]['text'].sample(
        min(5, len(df[df['Pattern Category'] == category])),
        random_state=42
    )

    for text in samples:
        print("-", text)

df['text_length'] = df['text'].str.len()

print("Text length statistics:")
print(df['text_length'].describe())

print("Shortest text:")
print(df.loc[df['text_length'].idxmin(), 'text'])

print("\nLongest text:")
print(df.loc[df['text_length'].idxmax(), 'text'])

"""text cleaning

"""

import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z0-9\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

df['clean_text'] = df['text'].apply(clean_text)

df[['text', 'clean_text']].head(10)

print("Original text:")
print(df['text'].iloc[0])

print("\nCleaned text:")
print(df['clean_text'].iloc[0])

X = df['clean_text']
y = df['label']

print("Number of text samples:", len(X))
print("Number of labels:", len(y))

page_label_check = df.groupby('page_id')['label'].nunique()

print("Pages with only one label:", (page_label_check == 1).sum())
print("Pages with multiple labels:", (page_label_check > 1).sum())

"""training & testing"""

from sklearn.model_selection import train_test_split

X = df['clean_text']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

"""TF-IDF"""

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

print("Training data shape:", X_train_tfidf.shape)
print("Testing data shape:", X_test_tfidf.shape)

"""logistic regression"""

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train_tfidf, y_train)

print("Model training completed!")

"""prediction"""

y_pred = model.predict(X_test_tfidf)

print("Predictions completed!")
print(y_pred[:10])

"""accuracy"""

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("Accuracy percentage:", accuracy * 100)

"""evaluate"""

from sklearn.metrics import classification_report, confusion_matrix

print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

"""naive bayes"""

from sklearn.naive_bayes import MultinomialNB

nb_model = MultinomialNB()

nb_model.fit(X_train_tfidf, y_train)

print("Naive Bayes training completed!")

nb_pred = nb_model.predict(X_test_tfidf)

print("Predictions completed!")

nb_accuracy = accuracy_score(y_test, nb_pred)

print("Naive Bayes Accuracy:", nb_accuracy)
print("Accuracy percentage:", nb_accuracy * 100)

print(classification_report(y_test, nb_pred))

"""results"""

results = pd.DataFrame({
    'Model': ['Logistic Regression', 'Naive Bayes'],
    'Accuracy': [accuracy, nb_accuracy]
})

results['Accuracy (%)'] = results['Accuracy'] * 100

display(results)

new_texts = [
    "Hurry! Only 2 items left in stock!",
    "Limited time offer. Buy now before the deal ends!",
    "This product is available in three different sizes.",
    "The product is made from high quality cotton.",
    "Only 5 people are viewing this product right now!"
]

new_clean_texts = [clean_text(text) for text in new_texts]

new_tfidf = tfidf.transform(new_clean_texts)

predictions = model.predict(new_tfidf)

for text, prediction in zip(new_texts, predictions):
    if prediction == 1:
        result = "Dark Pattern"
    else:
        result = "Not Dark Pattern"

    print("Text:", text)
    print("Prediction:", result)
    print()

"""confusion matrix"""

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

ConfusionMatrixDisplay.from_predictions(
    y_test,
    y_pred,
    display_labels=["Not Dark Pattern", "Dark Pattern"]
)

plt.title("Confusion Matrix - Logistic Regression")
plt.show()

"""result table"""

from sklearn.metrics import precision_score, recall_score, f1_score

precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

results = pd.DataFrame({
    'Metric': ['Accuracy', 'Precision', 'Recall', 'F1-Score'],
    'Score': [accuracy, precision, recall, f1]
})

results['Percentage'] = results['Score'] * 100

display(results)

"""saving"""

import joblib

joblib.dump(model, 'dark_pattern_model.pkl')
joblib.dump(tfidf, 'tfidf_vectorizer.pkl')

print("Model and TF-IDF vectorizer saved successfully!")

import os

print("Model exists:", os.path.exists('dark_pattern_model.pkl'))
print("Vectorizer exists:", os.path.exists('tfidf_vectorizer.pkl'))

"""final detector"""

def detect_dark_pattern(text):
    cleaned_text = clean_text(text)
    text_tfidf = tfidf.transform([cleaned_text])
    prediction = model.predict(text_tfidf)[0]

    if prediction == 1:
        return "Dark Pattern"
    else:
        return "Not Dark Pattern"

print(detect_dark_pattern("Hurry! Only 2 items left!"))
print(detect_dark_pattern("This phone has a 5000mAh battery."))
print(detect_dark_pattern("Limited time offer, buy now!"))
print(detect_dark_pattern("This shirt is available in five sizes."))

feature_names = tfidf.get_feature_names_out()
coefficients = model.coef_[0]

word_weights = pd.DataFrame({
    'Word': feature_names,
    'Weight': coefficients
})

print("Words indicating Dark Pattern:")
display(word_weights.sort_values('Weight', ascending=False).head(15))

print("Words indicating Not Dark Pattern:")
display(word_weights.sort_values('Weight').head(15))

"""Detector"""

text = input("Enter an e-commerce message: ")

cleaned = clean_text(text)

text_tfidf = tfidf.transform([cleaned])

prediction = model.predict(text_tfidf)[0]

if prediction == 1:
    print("Prediction: Dark Pattern")
else:
    print("Prediction: Not Dark Pattern")